### ISSUE TITLE
Deploying manually without mutating admissions?

### ISSUE THREAD

**Issue by deitch** [newrelic/k8s-webhook#26]
Is it possible to deploy NewRelic for Kafka without mutating admissions? The admission just adds another container to the pod; can I manually specify the pod, or use my own CI process to inject it into the configuration? Can you post instructions on how to do so?

To be clear, this does _not_ require NRI on the host, as a sidecar container runs next to the Kafka container? We do have it on the host, but as this is Kubernetes, I cannot install the Kafka for NRI module on the host itself, as it might run on one or not another.

FYI, did read the Word doc written by Ian Kavanagh.

**Comment by mariomac** [comment]
Hi @deitch ,

you can deploy the `newrelic/k8s-nri-kafka` integration directly. You just need to provide your agent configuration via environment variables and the Kafka integration configuration in the `/etc/newrelic-infra/integrations.d/config.yml` file.

At the end of this message you have an example manual deployment file. Please refer to the following documents for more information about the configuration options:

* Configuring the agent: https://docs.newrelic.com/docs/infrastructure/install-configure-infrastructure/configuration/infrastructure-configuration-settings
* Configuring the kafka integration: https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/kafka-monitoring-integration

Example `nri-kafka.yml` manual deployment file:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: nri-kafka-example
  namespace: default
spec:
  containers:
    - name: k8s-nri-kafka
      image: newrelic/k8s-nri-kafka
      volumeMounts:
        - name: kafka-example-config-volume
          mountPath: "/etc/newrelic-infra/integrations.d"
      env:
        # Configuring the infra agent
        - name: NRIA_LICENSE_KEY
          value: "your NR Infrastructure license key"
  volumes:
    - name: kafka-example-config-volume
      configMap:
        name: kafka-example-config-volume
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-example-config-volume
  namespace: default
data:
  # configuring the nri-kafka integration
  config.yaml: |
    integration_name: com.newrelic.kafka
    instances:
   (.... your config.yml file contents go here...)
```

Then you just have to run `kubectl apply -f nri-kafka.yml`.
